// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPquPVm-9dVpQ2blj9VghgfaPqts3QjzU',
    appId: '1:121000829262:web:43f9bc4a62e1971f1abe1f',
    messagingSenderId: '121000829262',
    projectId: 'floworder-69027',
    authDomain: 'floworder-69027.firebaseapp.com',
    databaseURL: 'https://floworder-69027-default-rtdb.firebaseio.com',
    storageBucket: 'floworder-69027.firebasestorage.app',
    measurementId: 'G-JZ1N7SGGJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_JSt33M6aTJ62-Pd51nI5EprMjT9CToI',
    appId: '1:121000829262:android:c7f50c11b8ad642e1abe1f',
    messagingSenderId: '121000829262',
    projectId: 'floworder-69027',
    databaseURL: 'https://floworder-69027-default-rtdb.firebaseio.com',
    storageBucket: 'floworder-69027.firebasestorage.app',
  );
}
